import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { requirePermission } from "@/lib/auth/access";
import { getCustomerSegments } from "@/lib/customers/queries";
import { runInactivityEvaluation, saveSegment } from "./actions";
export const dynamic = "force-dynamic";
const exampleRules = '{"all":[{"field":"lifetime_spend_cents","operator":">=","value":50000}]}';
export default async function SegmentsPage() { await requirePermission("segments.manage", "/admin/segments"); const segments = await getCustomerSegments(); return <main className="mx-auto max-w-6xl px-5 py-10"><p className="text-sm font-black uppercase tracking-[0.2em] text-wayne-red">Customer intelligence</p><h1 className="mt-3 text-4xl font-black">Segments</h1><p className="mt-3 max-w-3xl text-wayne-muted">Rules evaluate against authoritative customer metrics. Saving a rule safely re-evaluates all customer memberships and records only true enter/exit changes.</p><Card className="mt-7 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-black">Inactivity evaluation</h2><p className="mt-1 text-sm text-wayne-muted">The scheduled nightly job calls this same server-side evaluator. Run it now after importing customers or for an operational check.</p></div><form action={runInactivityEvaluation}><Button type="submit">Run inactivity evaluation</Button></form></div></Card><div className="mt-6 grid gap-4">{segments.map((segment) => <SegmentForm key={segment.id} segment={segment} />)}</div><details className="mt-7"><summary className="cursor-pointer text-xl font-black">Create custom segment</summary><div className="mt-4"><SegmentForm segment={{ id: "", name: "", description: "", rules_json: JSON.parse(exampleRules), active: true, sort_order: 100, population: 0 }} /></div></details><Card className="mt-7 p-5 text-sm text-wayne-muted"><strong className="text-wayne-ink">Supported fields:</strong> lifetime_spend_cents, order_count, average_order_value_cents, orders_last_30_days, days_since_last_order, sms_marketing_opt_in, email_marketing_opt_in. Use an <code>all</code> array and operators <code>&gt;=</code>, <code>&lt;=</code>, <code>=</code>, or <code>!=</code>.</Card></main>; }
function SegmentForm({ segment }: { segment: { id: string; name: string; description: string; rules_json: Record<string, unknown>; active: boolean; sort_order: number; population: number } }) { return <Card className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-black">{segment.name || "New segment"}</h2>{segment.id ? <span className="rounded-full bg-wayne-red/10 px-3 py-1 text-sm font-bold text-wayne-red">{segment.population} active</span> : null}</div><form action={saveSegment} className="mt-4 grid gap-4"><input name="id" type="hidden" value={segment.id} /><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Name<input className="min-h-11 rounded-lg border border-wayne-border px-3 font-normal" defaultValue={segment.name} name="name" required /></label><label className="grid gap-2 text-sm font-semibold">Sort order<input className="min-h-11 rounded-lg border border-wayne-border px-3 font-normal" defaultValue={segment.sort_order} name="sort_order" type="number" /></label></div><label className="grid gap-2 text-sm font-semibold">Description<input className="min-h-11 rounded-lg border border-wayne-border px-3 font-normal" defaultValue={segment.description} name="description" /></label><label className="grid gap-2 text-sm font-semibold">Rules JSON<textarea className="min-h-32 rounded-lg border border-wayne-border p-3 font-mono text-xs font-normal" defaultValue={JSON.stringify(segment.rules_json, null, 2)} name="rules_json" required /></label><label className="flex items-center gap-2 text-sm font-semibold"><input defaultChecked={segment.active} name="active" type="checkbox" /> Active</label><div><Button type="submit">Save segment</Button></div></form></Card>; }
