import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { requirePermission } from "@/lib/auth/access";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { updateMenuItemAction } from "../../actions";
import { MenuItemForm, type MenuItemInitial } from "../../menu-item-form";

export const metadata: Metadata = { title: "Edit menu item" };
type ItemRow = { id: string; category_id: string; name: string; description: string; image_alt: string; base_price_cents: number; tax_category: string; included_count_label: string; sold_out: boolean; customer_visible: boolean; pos_visible: boolean; featured: boolean; kitchen_route: string | null; available_days: number[]; available_start: string | null; available_end: string | null; sort_order: number };
type VariantRow = { name: string; price_cents: number; sku: string | null };
type LinkRow = { modifier_group_id: string; sort_order: number };
type GroupRow = { id: string; name: string; customer_label: string; min_select: number; max_select: number; required: boolean; allow_quantities: boolean };
type ChoiceRow = { modifier_group_id: string; name: string; price_delta_cents: number; default_selected: boolean; sort_order: number };

export default async function EditMenuItemPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; await requirePermission("menu.manage", `/admin/menu/items/${id}`); const supabase = await createServerSupabaseClient();
  const [{ data: itemData }, { data: categoryData }, { data: variantData }, { data: linkData }] = await Promise.all([supabase.from("menu_items").select("id,category_id,name,description,image_alt,base_price_cents,tax_category,included_count_label,sold_out,customer_visible,pos_visible,featured,kitchen_route,available_days,available_start,available_end,sort_order").eq("id", id).maybeSingle(), supabase.from("menu_categories").select("id,name").is("archived_at", null).order("sort_order"), supabase.from("menu_item_variants").select("name,price_cents,sku").eq("menu_item_id", id).eq("active", true).is("archived_at", null).order("sort_order"), supabase.from("menu_item_modifier_groups").select("modifier_group_id,sort_order").eq("menu_item_id", id).eq("active", true).order("sort_order")]);
  if (!itemData) notFound(); const item = itemData as ItemRow; const links = (linkData ?? []) as LinkRow[]; const groupIds = links.map((link) => link.modifier_group_id);
  const [{ data: groupData }, { data: choiceData }] = groupIds.length ? await Promise.all([supabase.from("modifier_groups").select("id,name,customer_label,min_select,max_select,required,allow_quantities").in("id", groupIds).eq("active", true), supabase.from("modifier_choices").select("modifier_group_id,name,price_delta_cents,default_selected,sort_order").in("modifier_group_id", groupIds).eq("active", true).is("archived_at", null).order("sort_order")]) : [{ data: [] }, { data: [] }];
  const groups = (groupData ?? []) as GroupRow[]; const choices = (choiceData ?? []) as ChoiceRow[]; const initial: MenuItemInitial = { ...item, image_alt: item.image_alt, base_price: (item.base_price_cents / 100).toFixed(2), kitchen_route: item.kitchen_route ?? "", available_start: item.available_start?.slice(0,5) ?? "", available_end: item.available_end?.slice(0,5) ?? "", variants: ((variantData ?? []) as VariantRow[]).map((variant) => ({ name: variant.name, price: (variant.price_cents / 100).toFixed(2), sku: variant.sku ?? "" })), modifier_groups: links.map((link) => groups.find((group) => group.id === link.modifier_group_id)).filter((group): group is GroupRow => Boolean(group)).map((group) => ({ name: group.name, customer_label: group.customer_label, min_select: group.min_select, max_select: group.max_select, required: group.required, allow_quantities: group.allow_quantities, choices: choices.filter((choice) => choice.modifier_group_id === group.id).map((choice) => ({ name: choice.name, price: (choice.price_delta_cents / 100).toFixed(2), default_selected: choice.default_selected })) })) };
  return <main className="mx-auto max-w-5xl px-5 py-10"><Link className="font-bold text-wayne-red" href="/admin/menu">← Menu</Link><h1 className="mt-4 text-4xl font-black">Edit {item.name}</h1><p className="mt-2 text-wayne-muted">Saving replaces active variant/modifier definitions with new archived-safe versions.</p><div className="mt-8"><MenuItemForm action={updateMenuItemAction.bind(null, id)} categories={(categoryData ?? []) as { id: string; name: string }[]} initial={initial} submitLabel="Save menu item" /></div></main>;
}
