import type { Metadata } from "next";
import { HoursList } from "@/components/site/hours-list";
import { SiteFooter } from "@/components/site/site-footer";
import { SiteHeader } from "@/components/site/site-header";
import { getStoreSettings } from "@/lib/content/queries";
import { formatAddress } from "@/lib/content/schemas";

export const dynamic = "force-dynamic";
export async function generateMetadata(): Promise<Metadata> { const settings = await getStoreSettings(); return { title: settings.seo_contact_title, description: settings.seo_contact_description, alternates: { canonical: settings.canonical_url ? `${settings.canonical_url}/contact` : "/contact" } }; }
export default async function ContactPage() { const settings = await getStoreSettings(); return <div className="storefront min-h-screen"><SiteHeader settings={settings} /><main id="main-content" className="mx-auto grid max-w-6xl gap-10 px-5 py-16 lg:grid-cols-2 lg:py-24"><section><p className="text-sm font-black uppercase tracking-[0.2em] text-wayne-red">Contact</p><h1 className="mt-3 text-5xl font-black tracking-tight">{settings.contact_heading}</h1><address className="mt-8 not-italic"><p className="text-xl leading-8">{formatAddress(settings)}</p>{settings.public_phone ? <a className="mt-4 block text-3xl font-black text-wayne-red" href={`tel:${settings.public_phone}`}>{settings.public_phone}</a> : null}{settings.public_email ? <a className="mt-2 block text-lg" href={`mailto:${settings.public_email}`}>{settings.public_email}</a> : null}</address>{settings.general_notice ? <p className="mt-8 rounded-2xl bg-wayne-warn-soft p-5 font-semibold">{settings.general_notice}</p> : null}</section><section className="rounded-3xl border border-wayne-border bg-white p-7 shadow-sm"><h2 className="text-2xl font-black">Regular hours</h2><div className="mt-5"><HoursList settings={settings} /></div>{settings.service_area_text ? <p className="mt-6 border-t border-wayne-border pt-5 text-wayne-muted">{settings.service_area_text}</p> : null}</section></main><SiteFooter settings={settings} /></div>; }
