import { z } from "zod";

export const customerSegmentSchema = z.object({ id: z.uuid(), name: z.string(), description: z.string(), rules_json: z.record(z.string(), z.unknown()), active: z.boolean(), sort_order: z.number().int(), population: z.number().int().nonnegative(), created_at: z.string(), updated_at: z.string() });
const segmentTagSchema = z.object({ id: z.uuid(), name: z.string() });
export const customerListItemSchema = z.object({ id: z.uuid(), first_name: z.string(), last_name: z.string(), phone_normalized: z.string(), email_normalized: z.string().nullable(), first_order_at: z.string().nullable(), last_order_at: z.string().nullable(), order_count: z.number().int(), lifetime_spend_cents: z.number().int(), average_order_value_cents: z.number().int(), sms_marketing_opt_in: z.boolean(), email_marketing_opt_in: z.boolean(), created_at: z.string(), segments: z.array(segmentTagSchema) });
export const customerListSchema = z.object({ customers: z.array(customerListItemSchema), total_count: z.number().int().nonnegative() });
export const customerDetailSchema = customerListItemSchema.extend({ addresses: z.array(z.object({ id: z.uuid(), label: z.string(), address1: z.string(), address2: z.string(), city: z.string(), state: z.string(), postal_code: z.string(), delivery_instructions: z.string(), is_default: z.boolean() }).passthrough()), consents: z.array(z.object({ id: z.uuid(), channel: z.string(), status: z.string(), source: z.string(), consent_text_version: z.string(), occurred_at: z.string() }).passthrough()), segments: z.array(z.object({ membership_id: z.uuid(), id: z.uuid(), name: z.string(), entered_at: z.string(), exited_at: z.string().nullable(), active: z.boolean() })), orders: z.array(z.object({ id: z.uuid(), order_number: z.string(), placed_at: z.string().nullable(), status: z.string(), source: z.string(), fulfillment_type: z.string(), total_cents: z.number().int() })), events: z.array(z.object({ id: z.uuid(), event_type: z.string(), segment_id: z.uuid().nullable(), metadata: z.record(z.string(), z.unknown()), occurred_at: z.string() })) });
export type CustomerSegment = z.infer<typeof customerSegmentSchema>;
export type CustomerListItem = z.infer<typeof customerListItemSchema>;
export type CustomerDetail = z.infer<typeof customerDetailSchema>;
